DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `cat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`cat_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 100
  DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `p_id` INT(11) NOT NULL AUTO_INCREMENT,
  `p_name` VARCHAR(100) NOT NULL,
  `p_desc` VARCHAR(1000) NULL DEFAULT NULL,
  `p_price` DECIMAL(22,2) NOT NULL,
  `p_stock_quantity` INT(11) UNSIGNED NOT NULL,
  `p_img_url` VARCHAR(150) NOT NULL,
  `cat_id` INT(11) NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `p_id` (`p_id` ASC),
  CONSTRAINT fk_CatID FOREIGN KEY (cat_id)
  REFERENCES category(cat_id))
  ENGINE = InnoDB
  AUTO_INCREMENT = 17
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;