<?php

define("SITE_ROOT", realpath("../") . DIRECTORY_SEPARATOR);
define("CSS_ROOT", SITE_ROOT . "css" . DIRECTORY_SEPARATOR);
define("INCLUDES_ROOT", SITE_ROOT . "includes" . DIRECTORY_SEPARATOR);
define("DB_ROOT", SITE_ROOT . "db" . DIRECTORY_SEPARATOR);
define("ADMIN_ROOT", SITE_ROOT . "admin" . DIRECTORY_SEPARATOR);
define("CMS_ROOT", SITE_ROOT . "cms" . DIRECTORY_SEPARATOR);
define("IMG_ROOT", SITE_ROOT . "img" . DIRECTORY_SEPARATOR);

?>